# Generated by Django 5.0.6 on 2024-07-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_walletmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmodel',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
