# Generated by Django 5.0.6 on 2024-07-04 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_alter_walletmodel_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentHistoryModel',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField()),
                ('total_minutes', models.IntegerField()),
                ('withdrawal', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.customermodel')),
            ],
        ),
    ]
