# Generated by Django 5.0.6 on 2024-07-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_agenthistorymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenthistorymodel',
            old_name='user',
            new_name='agent',
        ),
    ]
