# Generated by Django 5.0.6 on 2024-07-05 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_remove_userhistorymodel_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPurchaseModel',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField(default=0)),
                ('total_minutes', models.IntegerField(default=0)),
                ('withdrawal_amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.customermodel')),
            ],
        ),
    ]
