# Generated by Django 5.0.6 on 2024-07-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_agentpurchasemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinsModel',
            fields=[
                ('coin_id', models.AutoField(primary_key=True, serialize=False)),
                ('coin_amount', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='agentpurchasemodel',
            old_name='purchase_id',
            new_name='agentpurchase_id',
        ),
    ]
