# Generated by Django 5.0.6 on 2024-07-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_coinsmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_mail', models.EmailField(max_length=254)),
                ('admin_password', models.CharField(max_length=100)),
            ],
        ),
    ]
