# Generated by Django 5.0.6 on 2024-07-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_adminmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmodel',
            old_name='admin_name',
            new_name='admin_first_name',
        ),
        migrations.AddField(
            model_name='adminmodel',
            name='admin_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
