# Generated by Django 5.0.6 on 2024-07-15 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_rename_admin_name_adminmodel_admin_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetailsModel',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('agora_channel_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='AdminApp.customermodel')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller', to='AdminApp.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='InboxModel',
            fields=[
                ('inbox_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_message', models.TextField()),
                ('last_sent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='InboxParticipantsModel',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.inboxmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.inboxmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.customermodel')),
            ],
        ),
    ]
