# Generated by Django 5.0.6 on 2024-07-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_calldetailsmodel_inboxmodel_inboxparticipantsmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPackageModel',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_price', models.FloatField()),
                ('message_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoinPackageModel',
            fields=[
                ('coin_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_price', models.FloatField()),
                ('total_coins', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customermodel',
            name='messages_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
