# Generated by Django 5.0.6 on 2024-07-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0013_chatpackagemodel_coinpackagemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpurchasemodel',
            name='total_messages_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agentpurchasemodel',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
