# Generated by Django 5.0.6 on 2024-07-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0014_agentpurchasemodel_total_messages_received_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentpurchasemodel',
            old_name='total_amount',
            new_name='call_amount',
        ),
        migrations.AddField(
            model_name='agentpurchasemodel',
            name='chat_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='walletmodel',
            name='wallet_coins',
            field=models.IntegerField(default=300, null=True),
        ),
    ]
