# Generated by Django 5.0.6 on 2024-07-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0016_remove_walletmodel_agent_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='messages_remaining',
        ),
        migrations.AlterField(
            model_name='userpurchasemodel',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='withdrawalhistorymodel',
            name='withdrawal_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
