# Generated by Django 5.0.6 on 2024-07-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0018_delete_coinsmodel_customermodel_is_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='customer_password',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='languages',
            field=models.CharField(choices=[('Both', 'Both'), ('Malayalam', 'Malayalam'), ('Tamil', 'Tamil')], default='Both', max_length=20),
        ),
    ]
