# Generated by Django 5.0.6 on 2024-07-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0019_remove_customermodel_customer_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletmodel',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
