# Generated by Django 5.0.6 on 2024-07-23 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0021_alter_messagemodel_created_at_agenttransactionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttransactionmodel',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='AdminApp.customermodel'),
        ),
        migrations.AddField(
            model_name='agenttransactionmodel',
            name='transaction_type',
            field=models.CharField(choices=[('Chat', 'Chat'), ('Call', 'Call')], max_length=10, null=True),
        ),
    ]
