# Generated by Django 5.0.6 on 2024-07-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0022_agenttransactionmodel_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='adhaar_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='is_existing',
            field=models.BooleanField(default=False),
        ),
    ]
