# Generated by Django 5.0.6 on 2024-07-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0023_customermodel_adhaar_no_customermodel_is_existing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='adhaar_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
